-- MySQL Script generated by MySQL Workbench
-- 10/02/14 20:44:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema genesis-rebirth
-- -----------------------------------------------------
-- Create and developed by LoulouLMG.

-- -----------------------------------------------------
-- Schema genesis-rebirth
--
-- Create and developed by LoulouLMG.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `genesis-rebirth` ;
USE `genesis-rebirth` ;

-- -----------------------------------------------------
-- Table `genesis-rebirth`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `type` VARCHAR(25) NULL,
  `size` VARCHAR(25) NULL,
  `description` TEXT(1000) NULL,
  `img_blob` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`galaxy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`galaxy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galaxy_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_galaxy_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `genesis-rebirth`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_x` INT NULL,
  `position_y` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT(1000) NULL,
  `image_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_system_image1_idx` (`image_id` ASC),
  CONSTRAINT `fk_system_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `genesis-rebirth`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`system_entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`system_entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `position_u` INT NULL,
  `position_v` INT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT(1000) NULL,
  `system_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `galaxy_id` INT NOT NULL,
  PRIMARY KEY (`id`, `system_id`, `galaxy_id`),
  INDEX `fk_system_entity_system1_idx` (`system_id` ASC),
  INDEX `fk_system_entity_image1_idx` (`image_id` ASC),
  INDEX `fk_system_entity_galaxy1_idx` (`galaxy_id` ASC),
  CONSTRAINT `fk_system_entity_system1`
    FOREIGN KEY (`system_id`)
    REFERENCES `genesis-rebirth`.`system` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_entity_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `genesis-rebirth`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_entity_galaxy1`
    FOREIGN KEY (`galaxy_id`)
    REFERENCES `genesis-rebirth`.`galaxy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`planet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`planet` (
  `category` ENUM('VIABLE','NON_VIABLE') NULL,
  `atmosphere` ENUM('TOXIC','NORMAL','OFF') NULL,
  `temperature` SMALLINT(6) NULL,
  `radius` INT UNSIGNED NULL,
  `map_radius` ENUM('VERY_SMALL','SMALL','MEDIUM','BIG') NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_planet_system_entity`
    FOREIGN KEY (`id`)
    REFERENCES `genesis-rebirth`.`system_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`asteroid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`asteroid` (
  `amount` INT UNSIGNED NULL,
  `production` INT UNSIGNED NULL DEFAULT 0,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_asteroid_system_entity1`
    FOREIGN KEY (`id`)
    REFERENCES `genesis-rebirth`.`system_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`star`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`star` (
  `category` ENUM('I','II','III','IV') NULL,
  `power` INT UNSIGNED NULL,
  `radiation` INT UNSIGNED NULL,
  `production` INT UNSIGNED NULL DEFAULT 0,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_star_system_entity1`
    FOREIGN KEY (`id`)
    REFERENCES `genesis-rebirth`.`system_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`gas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`gas` (
  `amount` INT UNSIGNED NULL,
  `production` INT UNSIGNED NULL DEFAULT 0,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gas_system_entity1`
    FOREIGN KEY (`id`)
    REFERENCES `genesis-rebirth`.`system_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`whormhole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`whormhole` (
  `name` INT NULL,
  `range` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_whormhole_system_entity1_idx` (`id` ASC),
  CONSTRAINT `fk_whormhole_system_entity1`
    FOREIGN KEY (`id`)
    REFERENCES `genesis-rebirth`.`system_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`whormhole_has_whormhole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`whormhole_has_whormhole` (
  `start_id` INT NOT NULL,
  `end_id` INT NOT NULL,
  PRIMARY KEY (`start_id`, `end_id`),
  INDEX `fk_whormhole_has_whormhole_whormhole2_idx` (`end_id` ASC),
  INDEX `fk_whormhole_has_whormhole_whormhole1_idx` (`start_id` ASC),
  CONSTRAINT `fk_whormhole_has_whormhole_whormhole1`
    FOREIGN KEY (`start_id`)
    REFERENCES `genesis-rebirth`.`whormhole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_whormhole_has_whormhole_whormhole2`
    FOREIGN KEY (`end_id`)
    REFERENCES `genesis-rebirth`.`whormhole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serial` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `avatar` BLOB NULL,
  `homeworld_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_player_planet1_idx` (`homeworld_id` ASC),
  CONSTRAINT `fk_player_planet1`
    FOREIGN KEY (`homeworld_id`)
    REFERENCES `genesis-rebirth`.`planet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`ground`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`ground` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `ressource` ENUM('ORE','PRECIOUS_ORE','GAS') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`planet_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`planet_region` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genesis-rebirth`.`hexagonal_tile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genesis-rebirth`.`hexagonal_tile` (
  `id` INT NOT NULL,
  `checkpoint` TINYINT(1) NULL DEFAULT 0,
  `position_u` INT NULL,
  `position_v` INT NULL,
  `planet_id` INT NOT NULL,
  `ground_id` INT NOT NULL,
  `image_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`, `planet_id`, `region_id`),
  INDEX `fk_hexagonal_tile_planet1_idx` (`planet_id` ASC),
  INDEX `fk_hexagonal_tile_ground1_idx` (`ground_id` ASC),
  INDEX `fk_hexagonal_tile_image1_idx` (`image_id` ASC),
  INDEX `fk_hexagonal_tile_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_hexagonal_tile_planet1`
    FOREIGN KEY (`planet_id`)
    REFERENCES `genesis-rebirth`.`planet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hexagonal_tile_ground1`
    FOREIGN KEY (`ground_id`)
    REFERENCES `genesis-rebirth`.`ground` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hexagonal_tile_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `genesis-rebirth`.`image` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hexagonal_tile_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `genesis-rebirth`.`planet_region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
